### PR TITLE
Develop stream 2024-09-12

### LINKED ISSUE #478: [Issue]: Build with Clang >= 19 and libc++ fails on _VSTD macro
### Problem Description

Hi, 

`#include <thrust/type_traits/is_contiguous_iterator.h>` does not work with new versions of Clang when libc++ is enabled in compiler flags (i. e. `clang version 19.1.0+libcxx` `CXXFLAGS=--stdlib=libc++`).

The error is caused by lines:
https://github.com/ROCm/rocThrust/blob/6f47412b99e64a1d4681d9e0312132e4ad6042ec/thrust/type_traits/is_contiguous_iterator.h#L139-L144

Historical notes for _VSTD macro:
* Before Clang 14 it was defined as `std::_LIBCPP_ABI_NAMESPACE`
* [Clang 14 release notes](https://releases.llvm.org/14.0.0/projects/libcxx/docs/ReleaseNotes.html): "_VSTD is now an alias for std instead of std::_LIBCPP_ABI_NAMESPACE. This is technically not a functional change, except for folks that might have been using _VSTD in creative ways (which has never been officially supported)."
* Clang 19.1.0: _VSTD is fully removed as a part of [RFC proposal](https://discourse.llvm.org/t/rfc-clang-formatting-all-of-libc-once-and-for-all/75198) and https://github.com/llvm/llvm-project/pull/74331.

As seen on godbolt, `_VSTD` indeed was just `std` in Clang 17/18 - https://godbolt.org/z/nMWhj8PqT.

As ROCm stack effectively does not support anything earlier than Clang 17, is should be safe to replace `_VSTD` with `std`. Could you please replace one line?
```diff
-   _VSTD::__wrap_iter<Iterator>
+   std::__wrap_iter<Iterator>
```
That's _the only change_ required in rocThrust to fix compilation with Clang 19.1.0 (tested with pytorch). Thanks!

### Operating System

Gentoo

### CPU

-

### GPU

AMD Instinct MI300X

### ROCm Version

ROCm 6.2.2

### ROCm Component

rocThrust

### Steps to Reproduce

_No response_

### (Optional for Linux users) Output of /opt/rocm/bin/rocminfo --support

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by NB4444**
- Merged changes from upstream CCCL/thrust 2.4.0
- Synchronize rocThrust with Thrust v2.4.0 .
- Split the contents of HIPSTDPAR's forwarding header into several implementation headers.
- Fixed `--benchmark_format` from not working in benchmarks.
- Added a caching allocator to benchmarks to reduce noise and runtime.

The pipeline fails, because the version of rocPRIM used is not including [this commit](https://github.com/ROCm/rocPRIM/pull/605/commits/8ecad44bb564b4e6379a7a34b167f33667b5bcb3) yet.

---

Closes https://github.com/ROCm/rocThrust/issues/478.

### CODE REVIEW

**Comment by NB4444** [comment]
@AlexVlx any opinions about the HIPSTDPAR changes?

File: thrust/system/hip/hipstdpar/hipstdpar_lib.hpp [hunk 1]
```diff
@@ -2278,15 +2278,301 @@
...
+            }
+
+            auto        policy       = thrust::device;
+            size_t      storage_size = 0;
+            hipStream_t stream       = thrust::hip_rocprim::stream(policy);
+            bool        debug_sync   = THRUST_HIP_DEBUG_SYNC_FLAG;
+
+            hipError_t status;
+
+            status = rocprim::nth_element(
```
Comment (AlexVlx) [inline thrust/system/hip/hipstdpar/hipstdpar_lib.hpp]: I'd rather we didn't do things like so, if possible, but rather simply kept the ::std:: overloads as a very thin forwarder to thrust i.e. this should just forward to `thrust::nth_element(...)`, like the other algorithms did.

File: thrust/system/hip/hipstdpar/hipstdpar_lib.hpp [hunk 2]
```diff
@@ -2278,15 +2278,301 @@
...
+            const size_t n_index = n - 1;
+
+            auto        policy       = thrust::device;
+            size_t      storage_size = 0;
+            hipStream_t stream       = thrust::hip_rocprim::stream(policy);
+            bool        debug_sync   = THRUST_HIP_DEBUG_SYNC_FLAG;
+
+            hipError_t status;
+
+            status = rocprim::partial_sort(
```
Comment (AlexVlx) [inline thrust/system/hip/hipstdpar/hipstdpar_lib.hpp]: Idem.

File: thrust/system/hip/hipstdpar/hipstdpar_lib.hpp [hunk 3]
```diff
@@ -2278,15 +2278,301 @@
...
+            const size_t d_index = d_count - 1;
+
+            auto        policy       = thrust::device;
+            size_t      storage_size = 0;
+            hipStream_t stream       = thrust::hip_rocprim::stream(policy);
+            bool        debug_sync   = THRUST_HIP_DEBUG_SYNC_FLAG;
+
+            hipError_t status;
+
+            status = rocprim::partial_sort_copy(nullptr,
```
Comment (AlexVlx) [inline thrust/system/hip/hipstdpar/hipstdpar_lib.hpp]: Ibidem.

File: thrust/system/hip/hipstdpar/impl/batch.hpp [hunk 4]
```diff
@@ -0,0 +1,107 @@
...
+ *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ *  See the License for the specific language governing permissions and
+ *  limitations under the License.
+ */
+
+/*! \file thrust/system/hip/hipstdpar/include/batch.hpp
+ *  \brief <tt>Batch operations</tt> implementation detail header for HIPSTDPAR.
+ */
+
+#pragma once
```
Comment (AlexVlx) [inline thrust/system/hip/hipstdpar/impl/batch.hpp:19]: Doing the split is fine, since it aligns with Thrust convention, I guess; however, IMHO it'd be better if the master header (this), which is the object of implicit inclusion / is part of the public interface, would do nothing but include the split headers, as opposed to having any actual functionality. We could also probably guard the `interpose_allocations.hpp` one with its respective macros. Finally, we probably want to error on the impl headers if they're directly included without `__HIPSTDPAR__` being defined, as that would indicate user error.

**Review by AlexVlx — CHANGES_REQUESTED** [review]
Overall LGTM, thanks for doing this! There are a few nits / things I'd like to see changed though, so please consider them. Cheers!

File: README.md [hunk 5]
```diff
@@ -266,6 +266,39 @@ make -j4
 ./benchmarks/benchmark_thrust_bench
 ```
 
+## HIPSTDPAR
+rocThrust also hosts the header files for [HIPSTDPAR](https://rocm.blogs.amd.com/software-tools-optimization/hipstdpar/README.html#c-17-parallel-algorithms-and-hipstdpar).
+Within these headers, a great part of the C++ Standard Library parallel algorithms are overloaded so that rocThrust's and rocPRIM's implementations of those algorithms are used when they are invoked with the `parallel_unsequenced_policy` policy.
+When compiling with the proper flags (see [LLVM (AMD's fork) docs](https://github.com/ROCm/llvm-project/blob/rocm-6.2.x/clang/docs/HIPSupport.rst#implementation-driver) for the complete list), the HIPSTDPAR headers are implicitly included by the compiler, and therefore the execution of these parallel algorithms will be offloaded to AMD devices.
```
Comment (AlexVlx) [inline README.md]: Perhaps we should clarify that upstream supports this as well, it's just a case of the docs accidentally missing (they'll be the same there)

Comment (Beanavil) [reply README.md]: Sure, clarified it in the last commit!

File: thrust/system/hip/hipstdpar/impl/batch.hpp (hunk 4 above)
Comment (Beanavil) [reply thrust/system/hip/hipstdpar/impl/batch.hpp:19]: I have some questions about these suggestions:

> IMHO it'd be better if the master header (this), which is the object of implicit inclusion / is part of the public interface, would do nothing but include the split headers, as opposed to having any actual functionality

Do you mean that we should further split the master headers (the ones named after the C++ Standard Library categories for algorithms)?

> We could also probably guard the interpose_allocations.hpp one with its respective macros.

What macros do you refer to? IINM the `interpose_allocations.hpp` [is already guarded](https://github.com/ROCm/rocThrust/blob/8aff938930142937a527c1d54bc202ba57c26183/thrust/system/hip/hipstdpar/impl/interpose_allocations.hpp#L21-L22) by the `__HIPSTDPAR__` and
`__HIPSTDPAR_INTERPOSE_ALLOC__` macros (as it was before splitting `hipstdpar_lib.hpp`).

> Finally, we probably want to error on the impl headers if they're directly included without HIPSTDPAR being defined, as that would indicate user error.

And for this, I don't fully understand why would we need to error here. Originally there was no error handling in case that macro was not defined in the `hipstdpar_lib.hpp`, so I'm not sure why it would be done for the impl headers. Also, as I had understood it, the forwarding header was not intended to be included directly by users, but implicitly included by the compiler when specifying the `--hipstdpar` option (which also triggers the definition of the `__HIPSTDPAR__` macro). So if this is true (please correct me if not), then it wouldn't make sense to check for the definition of this macro IMHO.

File: thrust/system/hip/hipstdpar/hipstdpar_lib.hpp (hunk 1 above)
Comment (Beanavil) [reply thrust/system/hip/hipstdpar/hipstdpar_lib.hpp]: The reason behind forwarding to rocPRIM's algorithms is that currently rocThrust does not have support for the new Parallel STL algorithms that have been added to rocPRIM, as neither NVIDIA's Thrust nor CUB have implemented those yet.

**Comment by Beanavil** [comment]
@AlexVlx Hi! I answered your comments about the hipstdpar modifications, as I was the one responsible for those. Thanks for reviewing this :)

File: thrust/system/hip/hipstdpar/hipstdpar_lib.hpp (hunk 1 above)
Comment (AlexVlx) [reply thrust/system/hip/hipstdpar/hipstdpar_lib.hpp]: It'd be somewhat less cognitively challenging to have something like a stub `thrust::__nth_element(...)` call (we'd have to add the stubs, but you're already splitting into impl headers, no?) with a `// TODO: this'll go away once something happens` rather than having inline prim for a few algorithms, whilst most others forward to the higher level thrust interface. You'll note that the originals tried to keep away from directly doing any `hip*` stuff, and trying to do only C++ level handling before forwarding to Thrust. I am concerned with some problematic future, where some algorithms just doing a bunch of rocprim stuff inline because why not, some others keeping the forward to Thrust approach and, possibly, a 3rd category doing something else:) Perhaps I'm the odd person out with this preference / concern, though.

File: thrust/system/hip/hipstdpar/impl/batch.hpp (hunk 4 above)
Comment (AlexVlx) [reply thrust/system/hip/hipstdpar/impl/batch.hpp:19]: > Do you mean that we should further split the master headers (the ones named after the C++ Standard Library categories for algorithms)?

Not quite, what I meant is that the master header would pretty much be a list of `#include`s for the impl headers, with no declarations / definitions or, really, any substantive code living there. In essence, the most we'd do here is check for environmental macros / possibly declare some future config macros, if necessary. Does that make sense?

> What macros do you refer to? IINM the `interpose_allocations.hpp` [is already guarded](https://github.com/ROCm/rocThrust/blob/8aff938930142937a527c1d54bc202ba57c26183/thrust/system/hip/hipstdpar/impl/interpose_allocations.hpp#L21-L22) by the `__HIPSTDPAR__` and `__HIPSTDPAR_INTERPOSE_ALLOC__` macros (as it was before splitting `hipstdpar_lib.hpp`).

What I was suggesting as a possible alternative is to check for `__HIPSTDPAR_INTERPOSE_ALLOC__` in the master `hipstdpar_lib.hpp` header and do conditional include of the impl header in there, rather than guarding within it. This ties both to the point above re: what to do with the master header and to the one below about considering error-ing out.
 
> And for this, I don't fully understand why would we need to error here. Originally there was no error handling in case that macro was not defined in the `hipstdpar_lib.hpp`, so I'm not sure why it would be done for the impl headers. Also, as I had understood it, the forwarding header was not intended to be included directly by users, but implicitly included by the compiler when specifying the `--hipstdpar` option (which also triggers the definition of the `__HIPSTDPAR__` macro). So if this is true (please correct me if not), then it wouldn't make sense to check for the definition of this macro IMHO.

Whilst the vote of confidence is highly appreciated, I'd not take the original header to necessarily be complete / the best way to do things:) To wit, whilst the forwarding header was / is not meant to be included by users, that does not mean users won't do it (accidentally / intentionally). Error-ing out if the macro is not defined i.e. compilation for `hipstdpar` was not desired would guard against accidents, and will at least force intentional abusers to manually define the macro, which'd help with eventual debugging. I suggested it because I think it might be a time saver / inform users about things potentially going awry. Ultimately, it's up to you if you want to go in this direction.

Comment (Beanavil) [reply thrust/system/hip/hipstdpar/impl/batch.hpp:19]: > Not quite, what I meant is that the master header would pretty much be a list of #includes for the impl headers, with no declarations / definitions or, really, any substantive code living there. In essence, the most we'd do here is check for environmental macros / possibly declare some future config macros, if necessary. Does that make sense?

Oh alright, I was confused because the comment was made on `impl/batch.hpp`. But then, the master header `hipstdpar_lib.hpp` is already just a macro definition check (`__HIPSTDPAR__`) and a bunch of includes (for the `impl/` headers)

> What I was suggesting as a possible alternative is to check for __HIPSTDPAR_INTERPOSE_ALLOC__ in the master hipstdpar_lib.hpp header and do conditional include of the impl header in there, rather than guarding within it. This ties both to the point above re: what to do with the master header and to the one below about considering error-ing out.

> Whilst the vote of confidence is highly appreciated, I'd not take the original header to necessarily be complete / the best way to do things:) To wit, whilst the forwarding header was / is not meant to be included by users, that does not mean users won't do it (accidentally / intentionally). Error-ing out if the macro is not defined i.e. compilation for hipstdpar was not desired would guard against accidents, and will at least force intentional abusers to manually define the macro, which'd help with eventual debugging. I suggested it because I think it might be a time saver / inform users about things potentially going awry. Ultimately, it's up to you if you want to go in this direction.

Regarding those two points, the final logic should be then:
- Check in `hipstdpar_lib.hpp` if `__HIPSTDPAR__` is defined and include the `impl` headers if so, except `interpose_allocations.hpp` which only will be included if `__HIPSTDPAR_INTERPOSE_ALLOC__` is also defined.
- Inside each implementation header, check if `__HIPSTDPAR__` is defined and err if it's not.
- Additionally, in `interpose_allocations.hpp`, check if `__HIPSTDPAR_INTERPOSE_ALLOC__` is defined and err if not.

If that sounds good I'll add a commit with the changes

File: thrust/system/hip/hipstdpar/hipstdpar_lib.hpp (hunk 1 above)
Comment (Beanavil) [reply thrust/system/hip/hipstdpar/hipstdpar_lib.hpp]: Sorry for the late answer. After discussing it a little bit internally, we are unsure whether adding stubs to rocThrust would be ideal: the interface of Thrust is _based_ on that of the C++ Standard Library, but is not guaranteed to be exactly the same, so adding new API entries to rocThrust without knowing how Thrust would do it means that we may need to change this interface later (when Thrust adds these algorithms), which would be a breaking change. 
If the only reason for adding stubs to rocThrust is removing the calls to rocPRIM from hipstdpar, then it's probably not worth the risk. Perhaps you have other worries about this that we are failing to see?

Also, about this:
> I am concerned with some problematic future, where some algorithms just doing a bunch of rocprim stuff inline because why not, some others keeping the forward to Thrust approach and, possibly, a 3rd category doing something else:)

I don't think it should be a concern, as the missing algorithms are exclusively being added to rocPRIM.

Comment (AlexVlx) [reply thrust/system/hip/hipstdpar/hipstdpar_lib.hpp]: I guess I don't really follow what the risk is. We're not subcontractors for the Thrust development team, so having additional interfaces wouldn't be a problem, if we were to go in that direction. Furthermore, perhaps the point is lost, but what I am suggesting is to do something along the lines of `thrust::__nth_element_placeholder_stub_do_not_use_danger_will_robinson`, where the latter holds the current rocprim calls. The definition for this can and should live in the implementation header. It's primarily a matter of symmetry and code consistency, no other algorithm calls Prim inline.

File: thrust/system/hip/hipstdpar/impl/batch.hpp (hunk 4 above)
Comment (AlexVlx) [reply thrust/system/hip/hipstdpar/impl/batch.hpp:19]: This sounds great, thanks and apologies for adding work.

File: thrust/system/hip/hipstdpar/hipstdpar_lib.hpp (hunk 1 above)
Comment (Beanavil) [reply thrust/system/hip/hipstdpar/hipstdpar_lib.hpp]: Oh I see, so there would still be calls to rocPRIM from the hipstdpar implementation headers, only that the algorithms themselves would appear as if they call to rocThrust (but they call the stubs), right? If that's the case I see no problem adding this.

Comment (AlexVlx) [reply thrust/system/hip/hipstdpar/hipstdpar_lib.hpp]: Yup, that's it; then, when / if upstream adds these, we can just go and delete the double underscore prefix and the impl. This prevents folks (future maintainers) from having to ask themselves "should I just use PRIM here, or should I call Thrust", and at a glance makes it obvious we always call Thrust from the overloads. Thank you for taking the time to go through this, it's highly appreciated!

Comment (Beanavil) [reply thrust/system/hip/hipstdpar/hipstdpar_lib.hpp]: Added the changes for this! Please check if it fits your idea for the use of stubs.

File: thrust/system/hip/hipstdpar/impl/batch.hpp (hunk 4 above)
Comment (Beanavil) [reply thrust/system/hip/hipstdpar/impl/batch.hpp:19]: Also added the err logic discussed before

**Comment by Beanavil** [comment]
@AlexVlx just to check, are we good with the latest changes done to the hipstdpar headers? Just to know if more changes are needed or we can move on with this

**Review by AlexVlx — APPROVED** [review]
LGTM for the `hipstdpar` piece, many thanks for doing this!

**Comment by stanleytsang-amd** [comment]
Apologies for the delay on getting the PR approved.  Currently it looks like with the newer mainline images/compiler, there is a build error in rocThrust, but it's a compiler error not a rocThrust error.  I will submit a bug report to the compiler team.  I am able to build this a with 6.3 compiler and the tests pass in my limited testing, so I will merge this into develop for now.

**Review by stanleytsang-amd — APPROVED** [review]

**Comment by stanleytsang-amd** [comment]
Actually, wait.  I'm trying with a different compiler, this time from a 6.2.1 RC2 build, and im getting build errors that seem legitimate:
[ 17%] Building CXX object _deps/thread-building-blocks-build/test/CMakeFiles/conformance_arena_constraints.dir/conformance/conformance_arena_constraints.cpp.o
/src/rocThrust/build/_deps/thread-building-blocks-src/src/tbbmalloc_proxy/proxy.cpp:281:52: error: alias must point to a defined variable or function
  281 | void *aligned_alloc(size_t alignment, size_t size) __TBB_ALIAS_ATTR_COPY(memalign);
      |                                                    ^
/src/rocThrust/build/_deps/thread-building-blocks-src/src/tbbmalloc_proxy/proxy.cpp:74:56: note: expanded from macro '__TBB_ALIAS_ATTR_COPY'
   74 |     #define __TBB_ALIAS_ATTR_COPY(name) __attribute__((alias (#name)))
      |                                                        ^
/src/rocThrust/build/_deps/thread-building-blocks-src/src/tbbmalloc_proxy/proxy.cpp:281:52: note: the function or variable specified in an alias must refer to its mangled name
/src/rocThrust/build/_deps/thread-building-blocks-src/src/tbbmalloc_proxy/proxy.cpp:74:56: note: expanded from macro '__TBB_ALIAS_ATTR_COPY'
   74 |     #define __TBB_ALIAS_ATTR_COPY(name) __attribute__((alias (#name)))
      |                                                        ^
/src/rocThrust/build/_deps/thread-building-blocks-src/src/tbbmalloc_proxy/proxy.cpp:288:46: error: alias must point to a defined variable or function
  288 | void *__libc_calloc(size_t num, size_t size) __TBB_ALIAS_ATTR_COPY(calloc);
      |                                              ^
/src/rocThrust/build/_deps/thread-building-blocks-src/src/tbbmalloc_proxy/proxy.cpp:74:56: note: expanded from macro '__TBB_ALIAS_ATTR_COPY'
   74 |     #define __TBB_ALIAS_ATTR_COPY(name) __attribute__((alias (#name)))
      |                                                        ^
/src/rocThrust/build/_deps/thread-building-blocks-src/src/tbbmalloc_proxy/proxy.cpp:288:46: note: the function or variable specified in an alias must refer to its mangled name
/src/rocThrust/build/_deps/thread-building-blocks-src/src/tbbmalloc_proxy/proxy.cpp:74:56: note: expanded from macro '__TBB_ALIAS_ATTR_COPY'
   74 |     #define __TBB_ALIAS_ATTR_COPY(name) __attribute__((alias (#name)))
      |                                                        ^
/src/rocThrust/build/_deps/thread-building-blocks-src/src/tbbmalloc_proxy/proxy.cpp:289:54: error: alias must point to a defined variable or function
  289 | void *__libc_memalign(size_t alignment, size_t size) __TBB_ALIAS_ATTR_COPY(memalign);
      |                                                      ^
/src/rocThrust/build/_deps/thread-building-blocks-src/src/tbbmalloc_proxy/proxy.cpp:74:56: note: expanded from macro '__TBB_ALIAS_ATTR_COPY'
   74 |     #define __TBB_ALIAS_ATTR_COPY(name) __attribute__((alias (#name)))
      |                                                        ^
/src/rocThrust/build/_deps/thread-building-blocks-src/src/tbbmalloc_proxy/proxy.cpp:289:54: note: the function or variable specified in an alias must refer to its mangled name
/src/rocThrust/build/_deps/thread-building-blocks-src/src/tbbmalloc_proxy/proxy.cpp:74:56: note: expanded from macro '__TBB_ALIAS_ATTR_COPY'
   74 |     #define __TBB_ALIAS_ATTR_COPY(name) __attribute__((alias (#name)))
      |                                                        ^
/src/rocThrust/build/_deps/thread-building-blocks-src/src/tbbmalloc_proxy/proxy.cpp:290:35: error: alias must point to a defined variable or function
  290 | void *__libc_pvalloc(size_t size) __TBB_ALIAS_ATTR_COPY(pvalloc);
      |                                   ^
/src/rocThrust/build/_deps/thread-building-blocks-src/src/tbbmalloc_proxy/proxy.cpp:74:56: note: expanded from macro '__TBB_ALIAS_ATTR_COPY'
   74 |     #define __TBB_ALIAS_ATTR_COPY(name) __attribute__((alias (#name)))
      |                                                        ^
/src/rocThrust/build/_deps/thread-building-blocks-src/src/tbbmalloc_proxy/proxy.cpp:290:35: note: the function or variable specified in an alias must refer to its mangled name
/src/rocThrust/build/_deps/thread-building-blocks-src/src/tbbmalloc_proxy/proxy.cpp:74:56: note: expanded from macro '__TBB_ALIAS_ATTR_COPY'
   74 |     #define __TBB_ALIAS_ATTR_COPY(name) __attribute__((alias (#name)))
      |                                                        ^
/src/rocThrust/build/_deps/thread-building-blocks-src/src/tbbmalloc_proxy/proxy.cpp:291:34: error: alias must point to a defined variable or function
  291 | void *__libc_valloc(size_t size) __TBB_ALIAS_ATTR_COPY(valloc);
      |                                  ^
/src/rocThrust/build/_deps/thread-building-blocks-src/src/tbbmalloc_proxy/proxy.cpp:74:56: note: expanded from macro '__TBB_ALIAS_ATTR_COPY'
   74 |     #define __TBB_ALIAS_ATTR_COPY(name) __attribute__((alias (#name)))
      |                                                        ^
/src/rocThrust/build/_deps/thread-building-blocks-src/src/tbbmalloc_proxy/proxy.cpp:291:34: note: the function or variable specified in an alias must refer to its mangled name
/src/rocThrust/build/_deps/thread-building-blocks-src/src/tbbmalloc_proxy/proxy.cpp:74:56: note: expanded from macro '__TBB_ALIAS_ATTR_COPY'
   74 |     #define __TBB_ALIAS_ATTR_COPY(name) __attribute__((alias (#name)))
@Beanavil @NB4444  What ROCm build are you using to compile rocThrust with?

**Comment by NB4444** [comment]
I had a look at it. We do use 6.2.1 in our CI in which it works. Was able to reproduce this on a machine. This has to do with TBB that is used in the hipstdpar. Did find somewhere that it has to use libstdc++11 or newer for oneTBB to work. Was not able to find a fix. Will discuss with @Beanavil on Monday.

**Comment by stanleytsang-amd** [comment]
@Beanavil I'm not sure if your latest commit to disable TBB tests changes anything, I still seeing the same error while trying to build rocThrust unit tests.  What does TBB_TEST control?  I do not see its use anywhere.  I will upload a docker image where I still see build errors.

**Comment by Beanavil** [comment]
Hi @stanleytsang-amd, the latest two commits do two things:
- avoid compiling the hipstdpar tests when the C++ STL implementation used is (probably) incompatible with openTBB
- does not allow oneTBB's (internal) tests to be built (because they are built [by default](https://github.com/oneapi-src/oneTBB/blob/master/CMakeLists.txt#L106)), this is because in my local setup I got build errors coming from these tests that really don't need to be built in our use-case

I was also able yesterday to access the pipeline output and the docker images to reproduce the errors, I give more details about what I could debug in my answer to your email.

**Review by NguyenNhuDi — APPROVED** [review]
Hi all, with the new compiler, I was able to build this PR on gfx1101 and gfx908 and all unit tests passed.

**Comment by stanleytsang-amd** [comment]
Tests also passed on gfx90a as well.  I do see test failures on gfx942 - however they are only seen in the new staging compiler docker image we're using.  They do not fail in any recent mainline build.  I think we can merge in this PR and #486 for now, and if these test failures show up in the future, we can fix it then.

**Comment by stanleytsang-amd** [comment]
Similarly, the test failures reporting in DevOps CI here do not show in any mainline build.  For record keeping purposes, the failing tests are
	 30 - for_each.hip (Failed)
	 88 - sort.hip (Subprocess aborted)
	 90 - sort_by_key_variable_bits.hip (Subprocess aborted)
	119 - interpose_compile.hip (Subprocess aborted)

I will also send detailed failure logs in an email.  They have not indicated what exact ROCm build they're using, but once we get that information we can do deeper debugging.
